name: Build|Test|Run

on: [push, pull_request]

jobs:
 linux-gcc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      
      - name: Build Kokkos with OpenMP
        shell: bash
        run: |
          cd 3rdparty/kokkos
          mkdir build
          cd build
          cmake .. \
              -DCMAKE_CXX_COMPILER=g++ \
              -DCMAKE_C_COMPILER=gcc \
              -DKokkos_ENABLE_OPENMP=ON
          make -j4
          cd ../../..
      
      - name: Build FDTD with GCC
        shell: bash
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          mkdir build
          cmake \
              -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_CXX_COMPILER=g++ \
              -B ${PWD}/build
          cmake --build ${PWD}/build --config Release
          find ${PWD}/build -name test_FDTD_method
      - name: Run tests with GCC
        shell: bash
        run: |
          ${PWD}/build/test/test_FDTD_method --gtest_repeat=2 --gtest_break_on_failure

      - name: Run kokkos_sample
        shell: bash
        run: |
          find ${PWD}/build -name kokkos_sample
          ${PWD}/bin/kokkos_sample
      
      - name: Run sample
        shell: bash
        run: |
          ${PWD}/bin/sample

      - name: Install Intel OneAPI (ifort)
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-compiler-fortran

      - name: Compile and Run Coarray program with ifx
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh intel64

          echo "--- Verifying installation ---"
          which ifx
          ifx -v

          echo "--- Compiling Coarray program ---"
          ifx -coarray ${PWD}/coarray/fdtd.F90 -o fdtd

          echo "--- Running Coarray program ---"
          export FOR_COARRAY_NUM_IMAGES=4
          ${PWD}/fdtd
