name: Build application

on: [push, pull_request]

jobs:
 linux-gcc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      
      - name: Build Kokkos with OpenMP
        shell: bash
        run: |
          cd 3rdparty/kokkos
          mkdir build
          cd build
          cmake .. \
              -DCMAKE_CXX_COMPILER=g++ \
              -DCMAKE_C_COMPILER=gcc \
              -DKokkos_ENABLE_OPENMP=ON
          make -j4
          cd ../../..
      
      - name: Build FDTD with GCC
        shell: bash
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          mkdir build
          cmake \
              -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_CXX_COMPILER=g++ \
              -B ${PWD}/build
          cmake --build ${PWD}/build --config Release
          find ${PWD}/build -name test_FDTD_method
      - name: Run tests with GCC
        shell: bash
        run: |
          ${PWD}/build/sln/test_FDTD_method/test_FDTD_method --gtest_repeat=2 --gtest_break_on_failure
